---
- name: Collect default set of facts
  hosts: junos-all
  connection: local
  gather_facts: no

  vars:
    ansible_connection: netconf

  tasks:
    - name: Collect default set of facts and configuration
      junos_facts: